### ISSUE TITLE
JSON Log Format

### ISSUE THREAD

**Issue by IrrationalKyo** [VeReMi-dataset/VeReMi#1]
Hello,

For each simulation scenario, I went to the `results` directory to get the 
What is the naming convention for the JSON files?
For instance, `JSONlog-0-7-A0.json`, is my understanding that 0 is the vehicle number and A0 indicates if this vehicle is an attacker correct? What does `7` indicate?
What is the `type` field for each packet mean?

**Comment by wmabebe** [comment]
I found this Readme separately.
https://veremi-dataset.github.io/

File structure
Each simulation log contains a ground truth file for every message and a set of message logs for every vehicle that received messages. The file name of a message log identifies the receiver by vehicle number and OMNeT++ module number, e.g., JSONlog-0-7-A0.json refers to the 0th vehicle with OMNeT++ module ID 7. The latter is the number also used to identify the sender as such in any reception log and the ground truth file. A0 refers to the fact that this vehicle is not an attacker (refer to the paper for a discussion of the attacks, or check out the source code below).

**Comment by Enough7** [comment]
See [here](https://github.com/VeReMi-dataset/veins/blob/24e49cb4a140419d9cc88f0bbe54990c4ac63007/src/veins/modules/application/attackerapp/AttackerApp.cc#L39)
